version: 1.0.'{build}'

image:
 - Visual Studio 2017

configuration:
  - Release

platform:
  - x86
  - x64

environment:
  VCPKG_ROOT: C:\tools\vcpkg

cache:
  - vcpkg -> appveyor.yml

build_script:
  - cmd: build-x86.bat
  - cmd: build-x64.bat