version: 1.0.'{build}'

image:
 - Visual Studio 2017

configuration: Release

platform: x64

cache:
  - vcpkg -> appveyor.yml

environment:
   VCPKG_ROOT: C:\tools\vcpkg

build_script:
  - cmd: echo %VCPKG_ROOT%
  - cmd: xcopy vcpkg c:\tools\vcpkg\ports /S /E /Y
  - cmd: vcpkg.exe install curl:x64-windows-static
  - cmd: vcpkg.exe install jansson:x64-windows-static
  - cmd: vcpkg.exe install libmicrohttpd:x64-windows-static
  - cmd: vcpkg.exe install pthreads:x64-windows-static
  - cmd: vcpkg.exe install yder:x64-windows-static
  - cmd: vcpkg.exe install orcania:x64-windows-static
  - cmd: vcpkg.exe install ulfius:x64-windows-static
  - cmd: cd app
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake .. -DCMAKE_BUILD_TYPE=Release -DVCPKG_TARGET_TRIPLET=x64-windows-static -G"Visual Studio 15 2017 Win64" -DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%/scripts/buildsystems/vcpkg.cmake
  - cmd: cmake --build . --target app --config Release
  - cmd: cmake -- build .
