version: 1.0.'{build}'

image:
 - Visual Studio 2017

configuration: Release
platform: x64

environment:
  VCPKG_ROOT: C:\tools\vcpkg

cache:
  - C:\Tools\vcpkg\installed -> appveyor.yml

before_build:
  - cmd: cd %VCPKG_ROOT%
  - cmd: git pull --quiet

build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: build-x86.bat
  - cmd: build-x64.bat
