version: 1.0.'{build}'

image:
 - Visual Studio 2017

configuration: Release

platform: x64

cache:
  - vcpkg -> appveyor.yml

build_script:
  - cmd: vcpkg.exe install restinio:x64-windows-static
  - cmd: vcpkg.exe install curl:x64-windows-static
  - cmd: vcpkg.exe install jansson:x64-windows-static
  - cmd: vcpkg.exe install libmicrohttpd:x64-windows-static
  - cmd: vcpkg.exe install pthreads:x64-windows-static
